export default [
	{
		keyboardKeyName: 'a',
		keyboardKeyCode: 65,
		noteName: 'c',
		keyColor: 'white',
		pressed: false,
	},
	{
		keyboardKeyName: 'w',
		keyboardKeyCode: 87,
		noteName: 'c#',
		keyColor: 'black',
		pressed: false,
	},
	{
		keyboardKeyName: 's',
		keyboardKeyCode: 83,
		noteName: 'd',
		keyColor: 'white',
		pressed: false,
	},
	{
		keyboardKeyName: 'e',
		keyboardKeyCode: 69,
		noteName: 'd#',
		keyColor: 'black',
		pressed: false,
	},
	{
		keyboardKeyName: 'd',
		keyboardKeyCode: 68,
		noteName: 'e',
		keyColor: 'white',
		pressed: false,
	},
	{
		keyboardKeyName: 'f',
		keyboardKeyCode: 70,
		noteName: 'f',
		keyColor: 'white',
		pressed: false,
	},
	{
		keyboardKeyName: 't',
		keyboardKeyCode: 84,
		noteName: 'f#',
		keyColor: 'black',
		pressed: false,
	},
	{
		keyboardKeyName: 'g',
		keyboardKeyCode: 71,
		noteName: 'g',
		keyColor: 'white',
		pressed: false,
	},
	{
		keyboardKeyName: 'z',
		keyboardKeyCode: 90,
		noteName: 'g#',
		keyColor: 'black',
		pressed: false,
	},
	{
		keyboardKeyName: 'h',
		keyboardKeyCode: 72,
		noteName: 'a',
		keyColor: 'white',
		pressed: false,
	},
	{
		keyboardKeyName: 'u',
		keyboardKeyCode: 85,
		noteName: 'a#',
		keyColor: 'black',
		pressed: false,
	},
	{
		keyboardKeyName: 'j',
		keyboardKeyCode: 74,
		noteName: 'b',
		keyColor: 'white',
		pressed: false,
	},
	{
		keyboardKeyName: 'k',
		keyboardKeyCode: 75,
		noteName: 'c',
		keyColor: 'white',
		pressed: false,
	},
	{
		keyboardKeyName: 'o',
		keyboardKeyCode: 79,
		noteName: 'c#',
		keyColor: 'black',
		pressed: false,
	},
	{
		keyboardKeyName: 'l',
		keyboardKeyCode: 76,
		noteName: 'd',
		keyColor: 'white',
		pressed: false,
	},
	{
		keyboardKeyName: 'p',
		keyboardKeyCode: 80,
		noteName: 'd#',
		keyColor: 'black',
		pressed: false,
	},
	{
		keyboardKeyName: ';',
		keyboardKeyCode: 186,
		noteName: 'e',
		keyColor: 'white',
		pressed: false,
	},
];
